[build]
  command = "echo 'Building site...'"
  publish = "."

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  target = "node18"
  external_node_modules = ["pg", "bcryptjs", "jsonwebtoken"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
